import 'package:all/all.dart';
import 'package:right_case/data/base_api_service.dart';
import 'package:right_case/data/network_api_service.dart';
import 'package:right_case/resources/URLs/case_urls.dart';

import '../../../models/case_models/legal_task_model.dart';

class LegalTaskRepository {
  final BaseApiServices _services = NetworkApiServices();

  /// Computed fresh on every call from the actual device timezone, not
  /// hardcoded — correct for PKT today and safe if that ever changes.
  int get _utcOffsetHours => DateTime.now().timeZoneOffset.inHours;

  // ── Fetch bucketed board ─────────────────────────────────────
  Future<TaskBoardModel> getTaskBoard({String? caseId}) async {
    final queryParams = {
      'utc_offset_hours': '$_utcOffsetHours',
      if (caseId != null) 'case_id': caseId,
    };

    try {
      final response = await _services.getGetApiRequest(
        "${CaseUrls.baseUrl}/tasks/",
        CaseUrls.headers,
        query: queryParams,
      );

      return TaskBoardModel.fromJson(response);
    } catch (e) {
      debugPrint("Error in LegalTaskRepo:${e.toString()}");
      rethrow;
    }
  }

  // ── Create task ──────────────────────────────────────────────
  Future<LegalTaskModel> createTask({
    required String caseId,
    required String taskTitle,
    String? notes,
    required String priority,
    DateTime? dueDate,
    bool isAutoGenerated = false,
    String? sourceHearingId,
  }) async {
    final body = {
      'case_id': caseId,
      'task_title': taskTitle,
      if (notes != null) 'notes': notes,
      'priority': priority,
      // Always send UTC. dueDate from a picker is local — .toUtc() converts
      // it correctly; if it's already UTC this is a safe no-op.
      if (dueDate != null) 'due_date': dueDate.toUtc().toIso8601String(),
      'is_auto_generated': isAutoGenerated,
      if (sourceHearingId != null) 'source_hearing_id': sourceHearingId,
    };

    try {
      final response = await _services.getPostApiRequest(
        "${CaseUrls.baseUrl}/tasks/",
        CaseUrls.headers,
        body,
      );
      return LegalTaskModel.fromJson(response);
    } catch (e) {
      debugPrint("Error in LegalTaskRepo:${e.toString()}");
      rethrow;
    }
  }

  // ── Toggle completion ────────────────────────────────────────
  Future<LegalTaskModel> toggleCompletion({
    required String taskId,
    required bool isCompleted,
  }) async {
    final body = {"is_completed": isCompleted};
    try {
      final response = await _services.getPatchApiRequest(
        "${CaseUrls.baseUrl}/tasks/$taskId",
        CaseUrls.headers,
        body,
      );
      return LegalTaskModel.fromJson(response);
    } catch (e) {
      debugPrint("Error in LegalTaskRepo:${e.toString()}");
      rethrow;
    }
  }

  // ── Update task fields ───────────────────────────────────────
  Future<LegalTaskModel> updateTask({
    required String taskId,
    String? taskTitle,
    String? notes,
    String? priority,
    DateTime? dueDate,
  }) async {
    final body = <String, dynamic>{
      if (taskTitle != null) 'task_title': taskTitle,
      if (notes != null) 'notes': notes,
      if (priority != null) 'priority': priority,
      if (dueDate != null) 'due_date': dueDate.toUtc().toIso8601String(),
    };

    try {
      final response = await _services.getPatchApiRequest(
        "${CaseUrls.baseUrl}/tasks/$taskId",
        CaseUrls.headers,
        body,
      );
      return LegalTaskModel.fromJson(response);
    } catch (e) {
      debugPrint("Error in LegalTaskRepo:${e.toString()}");
      rethrow;
    }
  }

  // ── Delete task ──────────────────────────────────────────────
  Future<void> deleteTask(String taskId) async {
    try {
      await _services.getDeleteApiRequest(
        "${CaseUrls.baseUrl}/tasks/$taskId",
        CaseUrls.headers,
      );
    } catch (e) {
      debugPrint("Error in LegalTaskRepo:${e.toString()}");
      rethrow;
    }
  }
}
