# models/legal_task.py
#
# New table — run alembic migration after adding this.
# Follows the exact same conventions as your Hearing model.

import uuid
import enum

from sqlalchemy import (
    Boolean, Column, DateTime, Enum as SAEnum,
    ForeignKey, String, Text
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database.base import Base  # adjust to your project path


class TaskPriority(str, enum.Enum):
    high   = "high"
    medium = "medium"
    low    = "low"


class LegalTask(Base):
    __tablename__ = "legal_tasks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Ownership — every task belongs to a user and a case
    user_id = Column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    case_id = Column(
        UUID(as_uuid=True),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Core task fields
    task_title = Column(String,  nullable=False)
    notes      = Column(Text,    nullable=True)

    priority = Column(
        SAEnum(TaskPriority),
        default=TaskPriority.medium,
        nullable=False,
    )

    due_date = Column(DateTime(timezone=True), nullable=True)

    # Completion tracking
    is_completed  = Column(Boolean, default=False,  nullable=False)
    completed_at  = Column(DateTime(timezone=True), nullable=True)

    # Tracks whether this task was auto-generated by the hearing save hook
    # (vs. manually created by the lawyer)
    is_auto_generated = Column(Boolean, default=False, nullable=False)

    # If auto-generated: the hearing that triggered this task
    # Nullable — manually created tasks have no source hearing
    source_hearing_id = Column(
        UUID(as_uuid=True),
        ForeignKey("hearings.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Audit timestamps — same pattern as Hearing
    created_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    case    = relationship("Case",    back_populates="legal_tasks")
    user    = relationship("User",    back_populates="legal_tasks")
    hearing = relationship("Hearing", back_populates="legal_tasks", foreign_keys=[source_hearing_id])

