// lib/models/tasks/legal_task_models.dart
//
// Maps 1:1 to backend schemas in legal_task_schemas.py.
// All display helpers and computed properties live here.

// ─────────────────────────────────────────────
// Priority enum
// ─────────────────────────────────────────────
import 'dart:convert';

enum TaskPriority { high, medium, low }

extension TaskPriorityX on TaskPriority {
  String get label {
    switch (this) {
      case TaskPriority.high:
        return 'High';
      case TaskPriority.medium:
        return 'Medium';
      case TaskPriority.low:
        return 'Low';
    }
  }

  String get apiValue {
    switch (this) {
      case TaskPriority.high:
        return 'high';
      case TaskPriority.medium:
        return 'medium';
      case TaskPriority.low:
        return 'low';
    }
  }

  static TaskPriority fromString(String s) {
    switch (s.toLowerCase()) {
      case 'high':
        return TaskPriority.high;
      case 'low':
        return TaskPriority.low;
      default:
        return TaskPriority.medium;
    }
  }
}

// ─────────────────────────────────────────────
// Bucket enum — matches server-side buckets
// ─────────────────────────────────────────────
enum TaskBucket { overdue, thisWeek, upcoming, noDate, completed }

extension TaskBucketX on TaskBucket {
  String get label {
    switch (this) {
      case TaskBucket.overdue:
        return 'Overdue';
      case TaskBucket.thisWeek:
        return 'This week';
      case TaskBucket.upcoming:
        return 'Upcoming';
      case TaskBucket.noDate:
        return 'No date';
      case TaskBucket.completed:
        return 'Completed';
    }
  }
}

// ─────────────────────────────────────────────
// LegalTaskModel — maps to LegalTaskPublic
// ─────────────────────────────────────────────
class LegalTaskModel {
  final String id;
  final String caseId;
  final String taskTitle;
  final String? notes;
  final TaskPriority priority;
  final DateTime? dueDate;

  final bool isCompleted;
  final DateTime? completedAt;
  final bool isAutoGenerated;
  final String? sourceHearingId;

  final DateTime createdAt;
  final DateTime? updatedAt;

  // Denormalised from Case
  final String caseNumber;
  final String firstPartyName;
  final String? oppositePartyName;
  final String? courtName;

  const LegalTaskModel({
    required this.id,
    required this.caseId,
    required this.taskTitle,
    this.notes,
    required this.priority,
    this.dueDate,
    required this.isCompleted,
    this.completedAt,
    required this.isAutoGenerated,
    this.sourceHearingId,
    required this.createdAt,
    this.updatedAt,
    required this.caseNumber,
    required this.firstPartyName,
    this.oppositePartyName,
    this.courtName,
  });

  factory LegalTaskModel.fromJson(Map<String, dynamic> json) {
    return LegalTaskModel(
      id: json['id'] as String,
      caseId: json['case_id'] as String,
      taskTitle: json['task_title'] as String,
      notes: json['notes'] as String?,
      priority: TaskPriorityX.fromString(json['priority'] as String),
      dueDate: json['due_date'] != null
          ? DateTime.parse(json['due_date'] as String).toLocal()
          : null,
      isCompleted: json['is_completed'] as bool,
      completedAt: json['completed_at'] != null
          ? DateTime.parse(json['completed_at'] as String).toLocal()
          : null,
      isAutoGenerated: json['is_auto_generated'] as bool,
      sourceHearingId: json['source_hearing_id'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String).toLocal(),
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String).toLocal()
          : null,
      caseNumber: json['case_number'] as String,
      firstPartyName: json['first_party_name'] as String,
      oppositePartyName: json['opposite_party_name'] as String?,
      courtName: json['court_name'] as String?,
    );
  }

  // ── Display helpers ──────────────────────────────────────────

  String get caseTitle {
    if (oppositePartyName != null && oppositePartyName!.isNotEmpty) {
      return '$firstPartyName vs. $oppositePartyName';
    }
    return firstPartyName;
  }

  /// Human-readable due date — "Today", "Tomorrow", "26 Jun", "Overdue 3d"
  String get dueDateLabel {
    if (dueDate == null) return 'No date';
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final due = DateTime(dueDate!.year, dueDate!.month, dueDate!.day);
    final diff = due.difference(today).inDays;

    if (diff == 0) return 'Due today';
    if (diff == 1) return 'Due tomorrow';
    if (diff == -1) return 'Overdue 1 day';
    if (diff < 0) return 'Overdue ${diff.abs()} days';
    if (diff <= 7) return 'Due in $diff days';

    const months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec'
    ];
    return '${dueDate!.day} ${months[dueDate!.month - 1]}';
  }

  bool get isOverdue {
    if (isCompleted || dueDate == null) return false;
    return dueDate!.isBefore(DateTime.now());
  }

  /// Returns a copy with updated fields (for optimistic UI updates)
  LegalTaskModel copyWith({
    bool? isCompleted,
    DateTime? completedAt,
    String? taskTitle,
    String? notes,
    TaskPriority? priority,
    DateTime? dueDate,
  }) {
    return LegalTaskModel(
      id: id,
      caseId: caseId,
      taskTitle: taskTitle ?? this.taskTitle,
      notes: notes ?? this.notes,
      priority: priority ?? this.priority,
      dueDate: dueDate ?? this.dueDate,
      isCompleted: isCompleted ?? this.isCompleted,
      completedAt: completedAt ?? this.completedAt,
      isAutoGenerated: isAutoGenerated,
      sourceHearingId: sourceHearingId,
      createdAt: createdAt,
      updatedAt: DateTime.now(),
      caseNumber: caseNumber,
      firstPartyName: firstPartyName,
      oppositePartyName: oppositePartyName,
      courtName: courtName,
    );
  }
}

// ─────────────────────────────────────────────
// TaskBoardModel — maps to TaskBucketResponse
// ─────────────────────────────────────────────
class TaskBoardModel {
  final List<LegalTaskModel> overdue;
  final List<LegalTaskModel> thisWeek;
  final List<LegalTaskModel> upcoming;
  final List<LegalTaskModel> noDate;
  final List<LegalTaskModel> completed;

  final int overdueCount;
  final int thisWeekCount;
  final int totalOpen;

  const TaskBoardModel({
    required this.overdue,
    required this.thisWeek,
    required this.upcoming,
    required this.noDate,
    required this.completed,
    required this.overdueCount,
    required this.thisWeekCount,
    required this.totalOpen,
  });

  factory TaskBoardModel.fromJson(Map<String, dynamic> json) {
    List<LegalTaskModel> parse(String key) => (json[key] as List<dynamic>)
        .map((j) => LegalTaskModel.fromJson(j as Map<String, dynamic>))
        .toList();

    return TaskBoardModel(
      overdue: parse('overdue'),
      thisWeek: parse('this_week'),
      upcoming: parse('upcoming'),
      noDate: parse('no_date'),
      completed: parse('completed'),
      overdueCount: json['overdue_count'] as int,
      thisWeekCount: json['this_week_count'] as int,
      totalOpen: json['total_open'] as int,
    );
  }

  /// Returns a new board with a task replaced by its updated version.
  /// Used for optimistic UI updates without a full re-fetch.
  TaskBoardModel withUpdatedTask(LegalTaskModel updated) {
    List<LegalTaskModel> replaceIn(List<LegalTaskModel> list) =>
        list.map((t) => t.id == updated.id ? updated : t).toList();

    return TaskBoardModel(
      overdue: replaceIn(overdue),
      thisWeek: replaceIn(thisWeek),
      upcoming: replaceIn(upcoming),
      noDate: replaceIn(noDate),
      completed: replaceIn(completed),
      overdueCount: overdueCount,
      thisWeekCount: thisWeekCount,
      totalOpen: totalOpen,
    );
  }

  /// Returns a new board with a task removed from all buckets.
  TaskBoardModel withRemovedTask(String taskId) {
    List<LegalTaskModel> removeFrom(List<LegalTaskModel> list) =>
        list.where((t) => t.id != taskId).toList();

    return TaskBoardModel(
      overdue: removeFrom(overdue),
      thisWeek: removeFrom(thisWeek),
      upcoming: removeFrom(upcoming),
      noDate: removeFrom(noDate),
      completed: removeFrom(completed),
      overdueCount: overdueCount,
      thisWeekCount: thisWeekCount,
      totalOpen: totalOpen,
    );
  }

  /// Returns a new board with a new task prepended to the correct bucket.
  TaskBoardModel withNewTask(LegalTaskModel task) {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final weekEnd = today.add(const Duration(days: 7));

    if (task.dueDate == null) {
      return copyWithBucket(noDate: [task, ...noDate]);
    }
    final due =
        DateTime(task.dueDate!.year, task.dueDate!.month, task.dueDate!.day);
    if (due.isBefore(today)) {
      return copyWithBucket(overdue: [task, ...overdue]);
    }
    if (due.isBefore(weekEnd)) {
      return copyWithBucket(thisWeek: [task, ...thisWeek]);
    }
    return copyWithBucket(upcoming: [task, ...upcoming]);
  }

  TaskBoardModel copyWithBucket({
    List<LegalTaskModel>? overdue,
    List<LegalTaskModel>? thisWeek,
    List<LegalTaskModel>? upcoming,
    List<LegalTaskModel>? noDate,
    List<LegalTaskModel>? completed,
  }) {
    return TaskBoardModel(
      overdue: overdue ?? this.overdue,
      thisWeek: thisWeek ?? this.thisWeek,
      upcoming: upcoming ?? this.upcoming,
      noDate: noDate ?? this.noDate,
      completed: completed ?? this.completed,
      overdueCount: (overdue ?? this.overdue).length,
      thisWeekCount: (thisWeek ?? this.thisWeek).length,
      totalOpen: (overdue ?? this.overdue).length +
          (thisWeek ?? this.thisWeek).length +
          (upcoming ?? this.upcoming).length +
          (noDate ?? this.noDate).length,
    );
  }
}

class CreateTaskModel {
  final int caseId;
  final String taskTitle;
  final String? notes; // Optional
  final String priority;
  final DateTime? dueDate; // Optional
  final bool isAutoGenerated;
  final int? sourceHearingId; // Optional

  CreateTaskModel({
    required this.caseId,
    required this.taskTitle,
    this.notes,
    required this.priority,
    this.dueDate,
    this.isAutoGenerated = false,
    this.sourceHearingId,
  });

  /// Converts the class instance into your specific Map structure
  Map<String, dynamic> toMap() {
    return {
      'case_id': caseId,
      'task_title': taskTitle,
      if (notes != null) 'notes': notes,
      'priority': priority,
      if (dueDate != null) 'due_date': dueDate!.toIso8601String(),
      'is_auto_generated': isAutoGenerated,
      if (sourceHearingId != null) 'source_hearing_id': sourceHearingId,
    };
  }

  /// Converts the map payload straight to a JSON string for network requests
  String toJson() => json.encode(toMap());

  /// Factory constructor to create an instance back from a Map (optional but helpful)
  factory CreateTaskModel.fromMap(Map<String, dynamic> map) {
    return CreateTaskModel(
      caseId: map['case_id'] as int,
      taskTitle: map['task_title'] as String,
      notes: map['notes'] as String?,
      priority: map['priority'] as String,
      dueDate: map['due_date'] != null
          ? DateTime.parse(map['due_date'] as String)
          : null,
      isAutoGenerated: map['is_auto_generated'] as bool,
      sourceHearingId: map['source_hearing_id'] as int?,
    );
  }
}

class UpdateTaskModel {
  final String taskId;
  final String? taskTitle; // Optional
  final String? notes; // Optional
  final String? priority; // Optional
  final DateTime? dueDate; // Optional

  UpdateTaskModel({
    required this.taskId,
    this.taskTitle,
    this.notes,
    this.priority,
    this.dueDate,
  });

  /// Converts the class instance into a Map structure matching your API format
  Map<String, dynamic> toMap() {
    return {
      'task_id': taskId,
      if (taskTitle != null) 'task_title': taskTitle,
      if (notes != null) 'notes': notes,
      if (priority != null) 'priority': priority,
      if (dueDate != null) 'due_date': dueDate!.toIso8601String(),
    };
  }

  /// Converts the map payload straight into a JSON string
  String toJson() => json.encode(toMap());

  /// Factory constructor to create an instance back from a Map
  factory UpdateTaskModel.fromMap(Map<String, dynamic> map) {
    return UpdateTaskModel(
      taskId: map['task_id'] as String,
      taskTitle: map['task_title'] as String?,
      notes: map['notes'] as String?,
      priority: map['priority'] as String?,
      dueDate: map['due_date'] != null
          ? DateTime.parse(map['due_date'] as String)
          : null,
    );
  }
}
